spring:
  profiles:
    active: pro

myProps:
  ticketType:
    全价票: 全价票
    全票套票: 全价票
    身份证全价票: 全价票
    团体票: 全价票
    活动赠票: 全价票
    半价票: 半价票
    身份证半价票: 半价票
    散客半价票: 半价票
    团体半价票: 半价票
    半价套票: 半价票
    优惠票: 优惠票
    8.5折优惠票: 优惠票
    8折优惠票: 优惠票
    6折优惠票: 优惠票
    本地优惠票: 优惠票
    活动优惠票: 优惠票
    活动专用票: 优惠票
    优待票: 优惠票
    年卡: 年卡
    门票 观光车票（自）: 观光票
    门票 观光车票 保险(自): 观光票
    旅游年票专用车票: 观光票
    游艇散客票: 观光票
    动感飞艇散客票: 观光票
    玻璃栈道: 观光票
    身份证免票: 其他
    贵宾票: 其他
    身份证票: 其他
    预购票: 其他

  #本地/外地票配置
  localAndField:
    #神龙峡
    45e692de336b6d661d2a5d1907837af5:
      本地优惠票: 本地票
  touristType:
    #神龙峡
    45e692de336b6d661d2a5d1907837af5:
      管理卡: 成年人
      全价票: 成年人
      通行卡: 成年人
      本地优惠票: 成年人
      8.5折优惠票: 成年人
      8折优惠票: 成年人
      年卡: 成年人
      6折优惠票: 成年人
      半价票: 儿童、学生、中老年人
      身份证老年卡: 老年人


    #从移动运营商获取大数据-景区游客来源的景区
  bigPassenger:
    云台山景区: d5034caae86f1081e0e6ae5337e48e9f
    #华清宫景区: f561aaf6ef0bf14d4208bb46a4ccb3ad

  #通用景区
  commonScenic:
    云台山景区: d5034caae86f1081e0e6ae5337e48e9f
    神龙峡: 45e692de336b6d661d2a5d1907837af5
    华清宫景区: f561aaf6ef0bf14d4208bb46a4ccb3ad
    仙海: 4c68cea7e58591b579fd074bcdaff740
    西山: 38252f24c95a1d455b52942b3da41834
    卧龙	: 4ab2d1d4e72828a7ed358b30a67f6c37
    海螺沟: ac1d7d12306c5e60c89cfe9e6fc75027
    启封故园: df18633fa6ae3ac8a11e6a6317312336
    丹景山: b8d674653d82cfa939586ef5695fa4a1
    尉犁县: 6a9f0acb18afb6b1a6cf2200b7d6afbc
    罗浮山: 3d6a60810083d19b3f74589f610eb5a3
    眉山农业嘉年华景区: 8fa3e91b4da3c4912492640215ba63fa
#    石象湖景区: d80f699c062c8662fad3df86024e246c
#    华蓥山: c588f290c6aad177ec792eb990633b5c
#    乐山: 68f5fb5b4007ab8e68ad1c51c485abb1
#    昭君博物院: d04f86a2e4e440e991470c84fd45963c
    新疆赛里木湖: 28c8ee033e7286d791e9654929a08ecb
      #需要抓取景点数据的景区
  environment:
    names: pro










